### ISSUE TITLE
Validate HTTP status of data source URL

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#117]
Each JSON file for a city contains an URL in the metadata section pointing to the original data source. Here is an excerpt from _berlin.json_:

``` json
    "metadata": {
        "data_source": {
            "url": "http://daten.berlin.de/datensaetze/wochen-und-tr%C3%B6delm%C3%A4rkte"
        },
```
# Proposed validator
1. Collect the URLs from all city files
2. Execute a HTTP GET request on each URL
3. Check if the response code equals HTTP 200
4. Produce a warning if the response code indicates a redirection
5. Produce a build error if the response code indicates that the URL is no longer reachable

The validator should run on Travis CI, see [_package.json_](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/package.json).

**Comment by k-nut** [comment]
Just want to mention that this would be a good chance to use a HTTP head request instead of HTTP get.

**Comment by johnjohndoe** [comment]
First implementation in #174.
