### ISSUE TITLE
Bruchköbel and Hanau on wrong positions

### ISSUE THREAD

**Issue by AltNico** [wo-ist-markt/wo-ist-markt.github.io#122]
Both markets are in Somalia on the map. However, the coordinates are correct... Does I use a wrong format?

https://wo-ist-markt.de/#bruchk%C3%B6bel
https://wo-ist-markt.de/#hanau
https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/bruchk%C3%B6bel.json?short_path=77c081c#L6
https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/hanau.json?short_path=2cef9af#L6

Related to #119 and #121.

**Comment by k-nut** [comment]
That sounds like the latitude and the longitude field are switched.
