### ISSUE TITLE
Cities with Umlaute cannot be displayed

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#125]
Currently, cities which have an Umlaut in the name cannot be displayed. The following error is shown in the browser console when such a city is selected:

> Failure loading "cities/bruchköbel.json".
> Loading default city "karlsruhe" instead.

This error occurs since the website deployment changes recently, see #115.
I could see on the server that the file names are corrupted! Here is a listing of the cities/ folder on the new server:

```
berlin.json
bochum.json
bonn.json
bruchko??bel.json
chemnitz.json
cities.json
dortmund.json
dresden.json
duisburg.json
du??sseldorf.json
erlangen.json
essen.json
hanau.json
hilden.json
karlsruhe.json
kiel.json
ko??ln.json
langenfeld_rhld.json
leipzig.json
moers.json
mu??lheim-an-der-ruhr.json
mu??nchen.json
mu??nster.json
nersingen.json
neu-ulm.json
paderborn.json
rostock.json
schwerin.json
ulm.json
wiesbaden.json
witten.json
wuppertal.json
```

**Comment by k-nut** [comment]
This looks like a server misconfiguration or a problem with the deployment. I'll take a look at it.

**Comment by k-nut** [comment]
This seems to work now, doesn't it, @johnjohndoe?

**Comment by johnjohndoe** [comment]
I would say so. Maybe you can reference the commit where we implemented this here. Then we can close this issue.

**Comment by k-nut** [comment]
If I remember correctly this was fixed with a server change and not in code here. Therefore I am closing the issue. Feel free to reopen if you remember otherwise.
