### ISSUE TITLE
Link to duesseldorf.de changed

### ISSUE THREAD

**Issue by sfricke** [wo-ist-markt/wo-ist-markt.github.io#145]
The link to the Düsseldorf market administration changed from https://www.duesseldorf.de/verbraucherschutz/marktverwaltung/wochen.shtml to https://www.duesseldorf.de/verbraucherschutz/marktmanagement/wochenmaerkte/termine.html

**Comment by johnjohndoe** [comment]
@sfricke If you want you can update the link right [here](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/d%C3%BCsseldorf.json?short_path=67acfca#L397). /cc @cknebel

**Comment by sfricke** [comment]
@johnjohndoe Thank you! I did my very first pull request (#149) on github :-)

**Comment by johnjohndoe** [comment]
Nice!
