### ISSUE TITLE
Use logo for map markers

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#157]
The [basket logo](https://github.com/wo-ist-markt/wo-ist-markt-media/tree/master/assets) should be used for the map markers instead of the _shopping cart_ icon.

![Basket](https://github.com/wo-ist-markt/wo-ist-markt-media/blob/master/assets/basket-black-on-white.png?raw=true)

![wim-map-markers](https://cloud.githubusercontent.com/assets/144518/21712064/cc1ad7a6-d3f2-11e6-8b8e-deae84e1bc66.png)

**Comment by torfsen** [comment]
One thing to keep in mind is that if we want to support multiple types of markets (e.g. farmer's markets, flower markets, flea markets, etc., cf. #65) then we might want to use the marker icon to distinguish these types.

**Comment by johnjohndoe** [comment]
Good point. It would be really helpful if someone comes up with a design draft. Does anyone want to work on this or does anyone know a UI designer who wants to jump on-Korb? :joy_cat:

**Comment by tursics** [comment]
I'm here to jump in-Korb. I can design the markers and the icons

**Comment by johnjohndoe** [comment]
Nice. Feel free to assign the ticket to you whenever you want to start.
