### ISSUE TITLE
Explain map marker colors

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#158]
Currently, there is no legend for map markers and what their different colors mean.
We should communicate somewhat clearer which color maps to which filter setting.
Here is a quick draft:

![wim-legende](https://cloud.githubusercontent.com/assets/144518/21712511/85481f8e-d3f5-11e6-9911-590abc898913.png)

**Comment by Ryuno-Ki** [comment]
Is this still open for grabs for hacktoberfest?

**Comment by johnjohndoe** [comment]
@Ryuno-Ki Yes. You are welcome to discuss your ideas here.

**Comment by Ryuno-Ki** [comment]
Um, #312 :-)

**Comment by Ryuno-Ki** [comment]
I wasn't sure, whether this project is still active.
Basically, what I did was using the same classes Leaflet would be applying to the map and showed them in the header bar.
By putting them inside `<label>` clicking on them would also affect the radio buttons.

Where I am not quite happy with are explicit distances (read: `px` values) and the size of the marker compared to the text surrounding it.

I have some more ideas, but those would be outside of the scope of this issue. Shall I create new ones?

**Comment by k-nut** [comment]
@Ryuno-Ki yes, this project is still very much alive. Development slowed down a bit recently but please feel free to open new issues for your other ideas.

![typing GIF](https://media.giphy.com/media/13GIgrGdslD9oQ/giphy.gif)

**Comment by Ryuno-Ki** [comment]
Last issue addressed in #314

**Comment by johnjohndoe** [comment]
Looks like resolved to me.
