### ISSUE TITLE
Travis CI: Validation script does not fail when error is detected

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#195]
As noticed in the [initial pull request](https://travis-ci.org/wo-ist-markt/wo-ist-markt.github.io/builds/227154672?utm_source=github_status&utm_medium=notification) in #194 the validation script does **not** fail on Travis CI when an error is detected while checking the market data of a city.

First, an error is detected:

![travis1](https://cloud.githubusercontent.com/assets/144518/25557798/5b367a88-2d19-11e7-926d-91c4fae61c6b.png)

Then at the end of the script exit code 0 is return which is false!

![travis2](https://cloud.githubusercontent.com/assets/144518/25557799/5d491c72-2d19-11e7-8b72-a11f8968e94c.png)

**Comment by johnjohndoe** [comment]
@torfsen @k-nut @tursics @dirkschumacher @derhuerst :handshake: I could need some help on this one since this meanwhile affects all pull requests. If there is an error in the validation script Travis CI does not fail on it. Running the tests locally however the test suite fails as expected.

**Comment by johnjohndoe** [comment]
Yes, looks like we are back to normal. I also pushed [this branch](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/340e535ade313f64267deb511858f0dc7b5287c9) and saw the [validation failing](https://travis-ci.org/wo-ist-markt/wo-ist-markt.github.io/builds/231845501) as expected.
Do you know what exactly fixed it? Was it the [`&` to `&&` change](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/0a7982bc214fbef0a3a7bed2bd5049e0b518465d)?

**Comment by k-nut** [comment]
Maybe. It might also have been the [updated](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/3d304e15f38ce66f3fdfad300a40306b66c2c2f3) to a more recent version of node.

Let's keep an eye out of this ever happens again.

**Comment by johnjohndoe** [comment]
Yes. I think for now you can close the issue and get rid of the test branches. We can file another bug if it resurfaces.
