### ISSUE TITLE
wo-ist-markt.de yields 404

### ISSUE THREAD

**Issue by torfsen** [wo-ist-markt/wo-ist-markt.github.io#20]
Currently http://wo-ist-markt.de yields 404 for me.

**Comment by johnjohndoe** [comment]
Yes. I started experimenting with #4 yesterday night. I will revert the changes soon if I do not get it working.

**Comment by johnjohndoe** [comment]
I reverted the DNS settings. Everything back to normal. I might try again later.

**Comment by johnjohndoe** [comment]
Kloudsec fixed an issue on their European nodes. I will try again now.

**Comment by johnjohndoe** [comment]
Seems to work now. Also `https://`.

**Comment by johnjohndoe** [comment]
Thanks to @k-nut I switched the tile provider to SSL. Now it seems to be working.

![https-wim](https://cloud.githubusercontent.com/assets/144518/13979055/fe1fe7a6-f0d5-11e5-91d4-38fa1dfdb27e.png)

Please confirm here using the new GitHub upvoting feature.

**Comment by torfsen** [comment]
HTTP works for me.

HTTPS works, but the certificate is invalid since it doesn't contain the `wo-ist-markt.de` domain:
```
wo-ist-markt.de uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by johnjohndoe** [comment]
@torfsen Please try again. I just applied the change.

**Comment by torfsen** [comment]
Works perfectly, awesome!
