### ISSUE TITLE
Select field "other city" does not work on mobile

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#21]
I noticed that the **other city select box** added in #14 does not work when the website is visited on an Android phone (default browser). It does not respond when one touches it.
Also it should be larger on mobile to allow easier targeting.

![Website on smartphone](https://cloud.githubusercontent.com/assets/144518/13993257/df431264-f11f-11e5-8c64-e8514839d08e.png)

**Comment by torfsen** [comment]
PR #24 fixes this.
