### ISSUE TITLE
Marker icon broken on Android Chrome

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#225]
The new marker icons introduced in #223 do not show up on Chrome 60 on Android 6.0.1 on a Nexus 5.

![android-chrome](https://user-images.githubusercontent.com/144518/29811306-4cd3ede2-8ca3-11e7-9b20-2e91696b1546.png)

They icons show up correctly on Safari on ...

**Comment by tursics** [comment]
![screenshot_20170829-104602](https://user-images.githubusercontent.com/5406352/29812708-c803081e-8ca7-11e7-8816-111688c0763d.png)
Works on my BlackBerry with Android 6.0.1 and Chrome 60

**Comment by johnjohndoe** [comment]
Resolved: I deleted **all images** in the browser cache.
