### ISSUE TITLE
Improve string generating of city label

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#23]
Cities labels are currently parsed from the city .json file names in the `cities/` folder. As you can see from the screenshot there is some potential to improve the city label for "Neu-ulm".

![neu-ulm](https://cloud.githubusercontent.com/assets/144518/13993994/0a146742-f123-11e5-916d-77446e3c6354.png)

**Comment by torfsen** [comment]
As discussed in #29 we're going to explicitly list the city names instead. See #36.
