### ISSUE TITLE
Add a PR website

### ISSUE THREAD

**Issue by tursics** [wo-ist-markt/wo-ist-markt.github.io#238]
The info beamer at 34c3 shows the web url https://wo-ist-markt.de/#deinestadt but this url does not exists. Is it possible to show a PR site or PR content with this url? Or maybe a help-creating-new-city site?

Best,
Thomas

**Comment by johnjohndoe** [comment]
Thank you for bringing this up. Unknown URLs should be handled. This is basically the same idea as in issue #184. Please follow up there. If you agree, please close this issue.
