### ISSUE TITLE
Replace legend

### ISSUE THREAD

**Issue by torfsen** [wo-ist-markt/wo-ist-markt.github.io#25]
I think the legend is annoying, especially on mobile. It's also not very versatile and pretty limited in space, so I'd like to think about alternatives. I have something in mind for which I'll prepare a prototype, but I'd also like to hear other people's opinion about the legend and possible alternatives.

**Comment by johnjohndoe** [comment]
Another inspiration: @tursics uses a separate page for the _Impressum_ of his [_Kiez Karte_](http://kiez-karte.berlin).

**Comment by johnjohndoe** [comment]
@k-nut Any suggestions? You did this a couple of times in your projects I would think.

**Comment by johnjohndoe** [comment]
@torfsen Do you want to post what you have "in mind" as a sketch or similar?

**Comment by torfsen** [comment]
@johnjohndoe, yes, I'll prepare a prototype as soon as I find time for it :wink: 

My basic idea is to use a header at the top of the page for the most important information: The title (including the dropdown), the time selection radio buttons and a button for toggling a larger version of the header that includes details like the data source, GitHub links, etc.

**Comment by johnjohndoe** [comment]
Please consider moving less frequent consume parts to a separate page.
