### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#270]
Update the website **before May 25, 2018** ⏳ to comply with the [General Data Protection Regulation (GDPR)](https://ec.europa.eu/info/law/law-topic/data-protection_en).

- [ ] Let users opt-out and opt-in from being tracked by [Matomo analytics](https://matomo.org).
- [ ] Add a data privacy statement. (check OKFN website for current version)
- [ ] Check if Matomo is configured to mask two bytes of the users IP address.

See discussion in https://openknowledgegermany.slack.com in #gdpr channel. @knutator posted a text template there which might be used.

**Comment by johnjohndoe** [comment]
# Related
- [pretix and GDPR, 11.05.2018](https://pretix.eu/about/de/blog/20180511-gdpr/)

**Comment by dirkschumacher** [comment]
Why not just remove Matomo and republish?

**Comment by johnjohndoe** [comment]
I can't say if this would be enough to be compliant with the law - IANAL.
I prefer that whoever works on the issue does a bit of research to be sure.

**Comment by knutator2** [comment]
to make the Website Matomo Compliant only the snippet from @tursics is necessary, but @johnjohndoe is right. To make the page GDPR compliant, a data privacy statement is necessary. We updated our data privacy for OKFN at [okfn.de](https://okfn.de) accordingly, so we could use it and extend it with a paragraph, explaining the page is hosted via github.

**Comment by knutator2** [comment]
ah perfect, then only the maintainer in the top part needs to be changed

**Comment by johnjohndoe** [comment]
Meanwhile, the OKFN tends to switch to opt-in for Matomo. (Michael Peters)
- [Tracking nur noch mit Opt-In? Kritische Anmerkungen zum DSK-Papier](https://www.datenschutzbeauftragter-info.de/tracking-nur-noch-mit-opt-in-kritische-anmerkungen-zum-dsk-papier/)

If anyone wants to work on the GDPR topic so the website can go **online** again please do so.
I will **not** be able to work on the issue all over July.

**Comment by johnjohndoe** [comment]
# Current state of the website

![website](https://user-images.githubusercontent.com/144518/46476234-e8afac80-c7e7-11e8-83c8-74569021cc65.png)
