### ISSUE TITLE
Use a stable sort for entries in cities.json for easier diffs

### ISSUE THREAD

**Issue by k-nut** [wo-ist-markt/wo-ist-markt.github.io#285]
> ... always sort the items in some reproducible manner so that the diffs are a bit shorter and easier to read? Now they sometimes seem bigger than they actually are because the order of items changed.

See https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/283#discussion_r258354322

**Comment by johnjohndoe** [comment]
Another [diff](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/78410286db74100342ff98bb2a270fdd5e97ecbb) which could be "optimized".

**Comment by johnjohndoe** [comment]
@NWuensche This is the issue I mentioned recently when we talked about the project.
