### ISSUE TITLE
Add control to switch city

### ISSUE THREAD

**Issue by torfsen** [wo-ist-markt/wo-ist-markt.github.io#3]
As [discussed previously](https://github.com/CodeforKarlsruhe/wo-ist-markt/pull/10#issuecomment-180984029) and [requested by @tursics](https://github.com/CodeforKarlsruhe/wo-ist-markt/issues/17):

We should add a control to switch between the available cities. We could simply make the city headline in the legend an (approppriately styled) dropdown menu.

**Comment by dirkschumacher** [comment]
Haven't seen this issue before I submitted this PR #14

**Comment by johnjohndoe** [comment]
Resolved in 6f802bea6c184ca5f3f35ec1d17e46ce1ce4c8a4.
