### ISSUE TITLE
Details URL for each market

### ISSUE THREAD

**Issue by mojoaxel** [wo-ist-markt/wo-ist-markt.github.io#318]
Feature Request:

**What?**
Make it possible to define an optional URL for each market with additional information.

**Why?**
Some markets have a website with additional information. It would be nice if these information could be added.

**Comment by johnjohndoe** [comment]
@mojoaxel Do you still want to work on this topic?

**Comment by mojoaxel** [comment]
I like the idea but I have no time ATM. Please ask again in like 2 weeks 😉

It should not be a big issue to implement this...

**Comment by Roshanjossey** [comment]
@mojoaxel, do you have a design in mind for this change?

![image](https://user-images.githubusercontent.com/8488446/91161518-22834800-e6cb-11ea-916b-f7a8efc3b166.png)


![image](https://user-images.githubusercontent.com/8488446/91161344-efd94f80-e6ca-11ea-8f2d-57fae5c524a5.png)

![image](https://user-images.githubusercontent.com/8488446/91161646-4e9ec900-e6cb-11ea-84cd-0eaad73249a4.png)

**Comment by mojoaxel** [comment]
@Roshanjossey Thanks!
1. My favorite! Maybe with a text like "zur Markbetreiber" or "weitere Informationen!?
2. Links can get quite long. If only the domain would be shown this could also work.
3. This is to redundant for my taste!

**Comment by Roshanjossey** [comment]
Hi @johnjohndoe, I'm having some trouble running this locally. I'm opening index.html in my local to try my changes. Please advise

**Comment by Roshanjossey** [comment]
@johnjohndoe, It's working for me now. Thank you

**Comment by mojoaxel** [comment]
This has been implemented by @Roshanjossey in #337 :tada:
