### ISSUE TITLE
Initialize map with bounding box

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#33]
I would like to discuss whether it makes more sense to use a [bounding box](http://leafletjs.com/reference.html#latlngbounds) instead of `coordinates` and `zoom_level` to exactly match the area of markets in a city. Dependent on the distribution of markets and the screen size locations are displayed suboptimal.

``` json
"map_initialization": {
    "coordinates": [
        13.383333,
        52.516667
    ],
    "zoom_level": 11
}
```

Proposal:

``` json
"map_initialization": {
    "bounding_box" : {
        "south_west" : {
            "latitude" : 52.464504,
            "longitude" : 13.282079
        },
        "north_east" : {
            "latitude" : 52.549808,
            "longitude" : 13.475550
        }
    }
}
```

What's your opinion on this?

**Comment by torfsen** [comment]
Yes, that's something that I also have been thinking about. A bounding box is a good idea -- we can then use Leaflet's [`fitBounds` function](http://leafletjs.com/reference.html#map-fitbounds) to ensure that the bounding box is visible.
