### ISSUE TITLE
Add Flea markets in Hamburg

### ISSUE THREAD

**Issue by Roshanjossey** [wo-ist-markt/wo-ist-markt.github.io#332]
We have information about flea markets in Hamburg at https://www.hamburg.de/flohmarkt/.

# Flea markets that can be added

 - [x] Flohschanze  - Neuer Kamp 30
 - [x] Flea Dome Bahrenfelder Trabrennbahn
 - [ ] Kreativhaus, Eimsbüttel
 - [ ] Culture flea market around the Museum of Labor,  Barmbek
 - [ ] Flea dome on the Horner Rennbahn
 - [ ] People & Markets, Norderstedt
 - [ ] People & Markets, Bramfeld
 - [ ] Women's flea market, Bergedorf
 - [ ] FleaZinn in the Wilhelmsburger Zinnwerke
 - [ ] People & Markets, Hummelsbüttel
 - [ ] Flea market and district meeting,  Barmbek
 - [ ] "Second Emma"  Marktkauf Center Bergedorf
 - [ ] Clothes, Alsterdorfer Markt
 - [ ] Flea market in Bill's commercial harbor, Rothenburgsort
 - [ ] Michelwiese flea market, Neustadt
 - [ ] Hobby musician flea market, Alsterdorf
 - [ ] People & Markets, Ohlsdorf

# Related
- For reference of changes see https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/333/files
- [Contribution guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md)

**Comment by johnjohndoe** [comment]
Hi @Roshanjossey. That's great. Please have a look at the existing entries for Hamburg ([hamburg.json](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/cities/hamburg.json?short_path=58fef46), [website](https://wo-ist-markt.de/#hamburg)) and add the missing onces and update outdated. Make sure to read the [contribution guide](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/CONTRIBUTING.md#market-data-contributions) - it explains how to do this. If anything is unclear I am happy to help.

**Comment by johnjohndoe** [comment]
You might also want to contact the people who [contributed markets for Hamburg](https://github.com/wo-ist-markt/wo-ist-markt.github.io/pulls?q=is%3Apr+label%3A%22City%3A+Hamburg%22+) before: @alarmschaben, @lundelius, @flightofthepenguin

**Comment by Roshanjossey** [comment]
@johnjohndoe, your contribution guide is excellent. Great job on that. :tada: 

I've a question about the precision of co-ordinates. When I check on OpenStreetMaps, I get points with five decimal points precision. (eg 53.57622,9.89171)

From what I read from this comic, it's good enough
![image](https://user-images.githubusercontent.com/8488446/91160276-7b51e100-e6c9-11ea-8f76-0a7213637e74.png)

**Comment by johnjohndoe** [comment]
@Roshanjossey So, what is your exact question? If you want to go with five decimal points, that's fine with me. If you do not see a disadvantage, go for it.

**Comment by Roshanjossey** [comment]
Gotcha, Yes, that was my question.

**Comment by johnjohndoe** [comment]
@Roshanjossey Are you still want to work on this issue? If not please close it.

**Comment by Roshanjossey** [comment]
@johnjohndoe, no, I don't intend to work on this. I started this more as an entry level issue so more people could get started with contributing to this project. Closing
