### ISSUE TITLE
replace moment.js

### ISSUE THREAD

**Issue by mojoaxel** [wo-ist-markt/wo-ist-markt.github.io#339]
[moment.js is deprecated](https://momentjs.com/docs/#/-project-status/). You should move to another library..

# TODOs
- Explain in this issue which alternative library is suitable and why. Is it well maintained? Pros & cons.

**Comment by jamessral** [comment]
I could replace it with `date-fns` if you would like

**Comment by johnjohndoe** [comment]
@mojoaxel Can you please moderate this issue? I do not have time these days.

**Comment by mojoaxel** [comment]
> I could replace it with date-fns if you would like

@jamessral `date-fns` look fine to me. [Day.js](https://day.js.org/) would be even easier because it has a compatible api. Feel free choose a suitable alternative an provide a pull-request, I'll be happy to review it!

**Comment by jamessral** [comment]
@mojoaxel The pros for `date-fns` are:
- It is one of the recommended libraries by the [Moment project](https://momentjs.com/docs/#/-project/status/])
- It is very modular and designed to be easy for code-splitting
- It uses an immutable API
- It has great docs
- It has good TS support

**Comment by jamessral** [comment]
I can also look into `Day.js` for sure.

**Comment by jamessral** [comment]
Day also looks quite good. I can work on converting this over to Day.js

**Comment by mojoaxel** [comment]
fixed by @jamessral with #343 :tada:
