### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by mojoaxel** [wo-ist-markt/wo-ist-markt.github.io#341]
At the moment external dependencies are stores/copied to the `libs` folder. This is not a good practice. Dependencies should be loaded from `node_modules` or even bundled.

**Comment by jamessral** [comment]
[Parcel](https://parceljs.org/) could potentially be an easy to use bundler for this project. It is easy to use at dev time and can be run as a script for builds quite easily too.

**Comment by mojoaxel** [comment]
I'm more a fan of [rollup](https://rollupjs.org/) for such small projects but I have no problem with a parcel implementation.
@jamessral Feel free to provide a pull request but make sure the deployment [deployment](https://github.com/wo-ist-markt/wo-ist-markt.github.io#deployment) is still functional!

**Comment by jamessral** [comment]
I've wanted to mess with rollup, so I could give that a try.

**Comment by Ryuno-Ki** [comment]
Perhaps worth to create a separate bundle before switching over completely?
Looks like it gets a bit hairy.

I could imagine a multi-step approach:
1. Bundle with rollup, but with copied files from lib (to introduce the bundler and configure it)
2. Replace files from libs with a `require()` statement (perhaps gradually)

CSS could be indeed a bit tricky (as stated in #346).

**Comment by jamessral** [comment]
I think that's certainly possible 👍

**Comment by johnjohndoe** [comment]
_Just to communicate it:_ I stay out of this discussion since I have too less knowledge / experience of what would be a state of the art solution here.

**Comment by jamessral** [comment]
The difficulty that I'm still having is the nature of the dependencies. The modules here expect to be put into a global namespace at the top level of the browser, but this is not how commonjs is working. I can `require` jquery and leaflet, but the leaflet extensions expect leaflet to be global available to monkey-patch when they initialize. They are trying to reach out to missing dependencies and don't seem to execute the same way.

**Comment by Ryuno-Ki** [comment]
What about `require` the dep and assign the variable to `window.leaflet`?

**Comment by mojoaxel** [comment]
@jamessral I'm looking into it...

**Comment by jamessral** [comment]
I tried, doing that, but assigning it to `window.L`, since the leaflet modules expect it to be `L`. I even have the global declaration in the rollup config. What ends up happening is that some, but not all, of the `control` module are missing in `L`.

**Comment by mojoaxel** [comment]
@jamessral Maybe you want to merge https://github.com/jamessral/wo-ist-markt.github.io/pull/1

**Comment by Ryuno-Ki** [comment]
Hm, what if you [create multiple bundles](https://rollupjs.org/guide/en/#configuration-files) (second code snippet mentions the use of an Array)?
One for each dependency, that gets outputted as script tag (so basically a noop).
Then, you could look whether you can bundle multiple plugins into one bundle and thus reduce the outputs (by creating a file that imports those dependencies).

The references PR looks okay from a glance over it (haven't tried it locally).

**Comment by jamessral** [comment]
I've merged in that branch, so I'll see what the result looks like and how it builds. Thanks, @mojoaxel!

**Comment by johnjohndoe** [comment]
Not sure if this is related. Can someone explain why [this pull request](https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/350) is [not building on the CI](https://travis-ci.org/github/wo-ist-markt/wo-ist-markt.github.io/builds/744637187)?

```
/home/travis/build/wo-ist-markt/wo-ist-markt.github.io/node_modules/jasmine/lib/loader.js:39
  return import(path);
         ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by johnjohndoe** [comment]
fyi, dev dependencies are resolved again: https://david-dm.org/wo-ist-markt/wo-ist-markt.github.io?type=dev

**Comment by johnjohndoe** [comment]
@mojoaxel Are we done here?

**Comment by mojoaxel** [comment]
I'll have a look again as soon as possible...

**Comment by johnjohndoe** [comment]
It looks like we can close this issue since #348 replaced initial work in #346. If someone has something left please comment here. Otherwise, I will close this issue in a few days. @mojoaxel, feel free to close your issue yourself.
