### ISSUE TITLE
Tooltips do not open on Safari

### ISSUE THREAD

**Issue by k-nut** [wo-ist-markt/wo-ist-markt.github.io#379]
Whiles testing #378 I noticed that when I open the currently deployed website in desktop Safari (Version 14.1.1 (16611.2.7.1.4)) and click a marker to open a tooltip nothing happens. On mobile Safari some of the tooltips open, some also open and close immediately afterwards - I couldn't figure out a pattern that causes this though.

This does not seem to be a problem in Chrome or Firefox.

**Comment by johnjohndoe** [comment]
Here is a few related posts:

- https://stackoverflow.com/questions/65369083/popup-does-not-open-when-clicking-on-marker-safari
- https://stackoverflow.com/questions/67406533/react-leaflet-popups-not-working-on-mobile-devices
