### ISSUE TITLE
Validate market data

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#44]
I am currently working on a script which will validate the market data. I start with approving the opening hours format. The script will be automatically executed on Travis CI whenever a pull request is created.

**Comment by torfsen** [comment]
Good idea! Please integrate your script into our current test setup, so that running `npm test` executes it.

**Comment by johnjohndoe** [comment]
@torfsen I push a draft to [this branch](https://github.com/wo-ist-markt/wo-ist-markt.github.io/tree/markets-validation-44). Can you please review this and tell me how I can integrate it with Travis CI?

**Comment by k-nut** [comment]
Created a PR for this #48 . Essentially it is just one line in the `.travis.yml`

**Comment by johnjohndoe** [comment]
Branch updated. Please review again.

**Comment by johnjohndoe** [comment]
Updated (renamed "warning" to "error" basically). Updated documentation.

**Comment by johnjohndoe** [comment]
@k-nut @tursics @dirkschumacher Please review.

**Comment by k-nut** [comment]
@johnjohndoe can you make this into a PR so that we can comment on your changes?

**Comment by johnjohndoe** [comment]
@k-nut Done in #63.
