### ISSUE TITLE
Doppelte Datentöpfe

### ISSUE THREAD

**Issue by 0xErnie** [wo-ist-markt/wo-ist-markt.github.io#442]
Moin,

ich bin auf euch über den rc3 gekommen und ich habe Fragen.

Warum pflegt ihr hier eure eigene Datenbasis, wenn es mit OpenStreetMap schon einen Datentopf für genau diese Daten gibt, die leichter gepflegt werden können und teilweise auch aktueller sind?
Klingt für mich wie doppelte Arbeit bei der Pflege.

Siehe https://farmshops.eu/ bzw https://github.com/CodeforKarlsruhe/direktvermarkter, die haben auch direkte Links zum Bearbeiten in OSM, falls man einen Fehler sieht.

Mein Vorschlag wäre: Entweder Projekt einstellen und z.B. zu Farmshops verlinken oder die Datenquelle umstellen.
Wenn 2., dann könnte man ggf auch nochmal untersuchen, wie man das aktuell halten der Daten optimieren kann.

Viele Grüße aus Hamburg

**Comment by johnjohndoe** [comment]
Hi @0xErnie. I hope it's okay when we stick to English - so people from different background can participate here.

Thanks for bringing up the topic. It has been discussed before. To avoid the duplication I like to invite you to to read up in issue #252 what was stated there.
I am happy to discuss old or new aspects or provide guidance if you want to contribute your ideas to this project.

Friendly end-of-the-year greetings from Berlin.

**Comment by johnjohndoe** [comment]
@0xErnie Are you interested to keep the discussion going? If not I would think we could close this issue.

**Comment by 0xErnie** [comment]
Moin,

sorry, gerade bei komplexen Themen bleibe ich lieber bei meiner Muttersprache um Missverständnisse zu vermeiden, wenn das geschriebenen statt dessen doppelt übersetzt werden müsste.

Was das verlinkte Ticket angeht: Da geht es um das Hinzufügen von Michzapfanlagen und Hofläden in die Karte was dem [inofiziellen Mission Statement](https://github.com/wo-ist-markt/wo-ist-markt.github.io/issues/252#issuecomment-380244898), so wie du es in dem Ticket erwähnst, leicht wiederspricht.

Ich glaube, dass die manuelle Pflege der Markdaten, so wie ihr sie erdacht habt, nur gut funktioniert, wenn es genug Leute gibt, die die Daten regelmäßig pflegen.
Die OpenStreetMap an sich bietet (genauso wie dieses Projekt) eine Möglichkeit Öffnungszeiten von Märkten einzutragen und zu aktualisieren.

Wenn sich jetzt Öffnungszeiten von Märkten ändern, so müssen sie immer doppelt gepflegt werden.
Wenn jemand die Daten bei OSM aktualisiert profitieren alle Nuzter der Karten davon, auch jene die z.B. OsmAnd nutzen.

Wäre es nicht cool, wenn die Leitlinien wie folgt wären:
* The project WIM provides it's visitors an easy way to find farmers market in their region, including opening hours.
* WIM indicates the visitors the freshnes of the information and it's source.
* If data is outdated or missing WIM provides the visitors an easy way to either update the information or mark them for review.

Derzeit habt ihr WIM auf mehrer Städte begrenzt, das könnte man sicher durch ein paar Filter beibehalten, für die Städte, bei denen ihr euch sicher seid, dass sie gut gepflegt werden.
Es gibt viele gute und nutzbare Programme, die auf den Daten von OSM basieren.

**Comment by johnjohndoe** [comment]
> Ich glaube, dass die manuelle Pflege der Markdaten [...] nur gut funktioniert, wenn es genug Leute gibt, die die Daten regelmäßig pflegen.

Ich stimme dir zu. Da es niemanden gibt, die/der sich um alle Städte kümmert, veraltet der Stand der statischen Daten sehr schnell. Nur in den Städten, in denen Personen aktiv sind, sind auch die Marktdaten aktuell.

> Die OpenStreetMap an sich bietet [...] eine Möglichkeit Öffnungszeiten von Märkten einzutragen und zu aktualisieren.

Das stimmt auch. Ich bin selbst bei OpenStreetMap aktiv. Ich nutze auch Programme, die auf der Datenbasis arbeiten. Ich sehe auch ganz klar die Doppelung und den Nachteil der statisch im Repository vorgehaltenen Daten.

> Derzeit habt ihr WIM auf mehrer Städte begrenzt [...]

Das ist Absicht. Es macht aus meiner Sicht keinen Sinn, Städte anzubieten, in denen sich niemand (nicht einmal initial) für die Marktdaten der Stadt interessiert.

In einem Aspekt unterscheidet sich dieses Projekt aber von anderen OpenStreetMap-Projekten. Wir versuchen, **offene Daten der Verwaltung** zu nutzen (und diese auf zugängliche Weise darzustellen). Würden wir die Darstellung "nur" auf OpenStreetMap-Daten basieren, dann geraten die Verwaltungsdaten vollkommen aus dem Fokus.
Was ich mir sehr gut vorstellen kann, ist ein **Synchronisationsmechanismus**, mit dem es möglich ist, Daten zwischen der Verwaltung und OpenStreetMap abzugleichen. Das hat seiner Zeit das Projekt [WheelMap](https://wheelmap.org) der @sozialhelden mit dem [POIchecker](https://github.com/sozialhelden/poichecker) gemacht, um Datenspenden abzugleichen. Das würde dazu beitragen, dass die Datenqualität verbessert wird und sich beide Erhebungen angleichen. Hier fehlt es wie so oft an **engagierten Personen**, die die Idee technisch umsetzen möchten. Unsere Webseite könnte dann langfristig auf OpenStreetMap als primäre Datenquelle umgestellt werden.
