### ISSUE TITLE
Default city is loaded when closing pop up with cross

### ISSUE THREAD

**Issue by joergreichert** [wo-ist-markt/wo-ist-markt.github.io#515]
How to reproduce:

1. select city diffent then Karsruhe, e.g.: https://www.wo-ist-markt.de/#bad-homburg
2. click on an entry at the map to open pop up
3. click on cross in the right upper corner to close the pop up

expected:

- stick to https://www.wo-ist-markt.de/#bad-homburg

actual:

- https://www.wo-ist-markt.de/#karlsruhe is loaded

**Comment by johnjohndoe** [comment]
Thanks for discovering this. Confirmed: same behavior for me here. Tested on Brave for Android.

**Comment by alexschnapper** [comment]
Hi, just manually retested on Firefox (mac) and also on Firefox (Android) and behaviour is like expected.

**Comment by johnjohndoe** [comment]
I am on vacation. Maybe @joergreichert can take over?

**Comment by alexschnapper** [comment]
@joergreichert Any chance of viewing this issue? :)

**Comment by johnjohndoe** [comment]
@alexschnapper I checked the behavior now on Brave on Ubuntu and Brave on Android. In both environments the website behaves as expected. Therefore, I close this issue now.
