### ISSUE TITLE
Time based market filtering broken

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#84]
I noticed that the time based filtering is not working. Although there are markets taking place right **now** **none** of the markets is put into the "Jetzt" category as shown in the screenshot for Berlin.

![markets-now-error](https://cloud.githubusercontent.com/assets/144518/14766301/f3f38d86-0a03-11e6-8989-a25ecec45676.png)

I checked the [commit when Berlin was added](https://github.com/wo-ist-markt/wo-ist-markt.github.io/commit/3e8bd9ef37ed83b0c33c6c01892f4c9c57a8a9b0) to the repository. It seems this feature has **never worked** - at least not for Berlin.

**Comment by k-nut** [comment]
If you are fine with making requests you could just use my new filter api. But this can probably also just as easily be solved in the frontend...

**Comment by dirkschumacher** [comment]
Why don't you just simply merge #39 ?

**Comment by johnjohndoe** [comment]
@k-nut I prefer fixing the bug before migrating the project to an external API.
@dirkschumacher I had no time to review the branch.
