### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Matthias84** [wo-ist-markt/wo-ist-markt.github.io#89]
It would be nice, if the page could become an unique favicon. So it's easier to recognize within a list of tabs, or as homescreen bookmark.

The green map marker would be an easy to realize icon?

**Comment by johnjohndoe** [comment]
Good idea. You could generate a favicon from the basket icon which can be found at the [GitHub organization](https://github.com/wo-ist-markt).

**Comment by torfsen** [comment]
@johnjohndoe: What is the license of that image? I like it and I think we could use it as the general logo for the site, however we need to make sure that we respect its license.

**Comment by Matthias84** [comment]
@torfsen Usually map marker / icon glyphs are licensed under PD / CC0 to avoid troubles and license clash. They are very basic bricks e.g. if you design an map style and thus they would heavily propagate an copyleft /copyright.

**Comment by torfsen** [comment]
@Matthias84: I was talking about our [organization logo](https://avatars3.githubusercontent.com/u/17050186?v=3&s=200), which is better suited for the task in my opinion.

**Comment by johnjohndoe** [comment]
I created the icon myself as a first version for a logo. I did not have time to refine it.

**Comment by dirkschumacher** [comment]
How about using something like this? http://www.favicon-generator.org/

We can then also add images for mobile clients as well.

**Comment by Matthias84** [comment]
I recommend to use an cooperate design, thus the logo should repeated at favicon, map, open graph ( #92 ). If you are unhappy with existing one, have a look [at nounproject](https://thenounproject.com/search/?q=shopping) or [openclipart](https://openclipart.org/search/?query=shopping) for adequate vector graphics. Personally I would choose a shopping basket / bag but not an trolley (which is used at malls / supermarkets only).

**Comment by torfsen** [comment]
@johnjohndoe Do you have a vector graphic version of the logo?

**Comment by johnjohndoe** [comment]
I created a separate ["media" repository](https://github.com/wo-ist-markt/wo-ist-markt-media) and put the files there.

**Comment by k-nut** [comment]
@Matthias84 do you want to create a PR that makes this into the favicon or should I take care of that?

**Comment by Matthias84** [comment]
Would be nice, if you could do the job :+1:
