### ISSUE TITLE
Deploy PR to S3 automatically

### ISSUE THREAD

**Issue by dirkschumacher** [wo-ist-markt/wo-ist-markt.github.io#95]
It would be great if whenever a Pull Request comes in, the content of the repository is copied to a S3 buckets, so it is easier to quickly review the changes without running a local server and checking out the branch.

Travis CI could be used for that but only for PRs from authors with write access for the main repository.
Alternative would be to write a small application that clones the PR's git repository into a S3 bucket whenever a new PR is opened or an existing one is updated.

Bonus points: the link to the PR website gets automatically posted to the PR discussion.

For example: 
- A new PR comes in with the ID 100.
- A few seconds later a bot posts a message to the PR discussion with this link: https://some-bucket.s3-website.eu-central-1.amazonaws.com/pull-request/pull/100/index.html
- ...
- New commits were pushed
- The S3 websites is automatically updated and reflects the current head of the branch

What do you think?

**Comment by torfsen** [comment]
Sounds nice-to-have but isn't really important from my point of view. If you'd like to implement it you're of course very welcome to do so :wink:

**Comment by k-nut** [comment]
I set up deployment with [netlify](https://netlify.com). They make the deployment process much easier and automatically create a new subdomain for every PR.
See https://history-api--wo-ist-markt.netlify.com/köln for an example.

**Comment by dirkschumacher** [comment]
I think we can close this.
